import Foundation

// Codable types that mirror Supabase table columns (snake_case).
// No Supabase SDK import needed — pure Foundation.
// See supabase/schema.sql for the corresponding table definitions.

// MARK: - User Profile DTO

struct UserProfileDTO: Codable {
    var id: String              // = Supabase auth user UUID (primary key)
    var displayName: String?
    var dateOfBirth: String?    // ISO-8601 full-date: "YYYY-MM-DD"
    var biologicalSex: String?
    var heightCm: Double?
    var currentWeightKg: Double?
    var targetWeightKg: Double?
    var preferredWeightUnit: String
    var preferredDistanceUnit: String
    var onboardingCompleted: Bool
    var onboardingStep: Int
    var updatedAt: String?

    enum CodingKeys: String, CodingKey {
        case id
        case displayName           = "display_name"
        case dateOfBirth           = "date_of_birth"
        case biologicalSex         = "biological_sex"
        case heightCm              = "height_cm"
        case currentWeightKg       = "current_weight_kg"
        case targetWeightKg        = "target_weight_kg"
        case preferredWeightUnit   = "preferred_weight_unit"
        case preferredDistanceUnit = "preferred_distance_unit"
        case onboardingCompleted   = "onboarding_completed"
        case onboardingStep        = "onboarding_step"
        case updatedAt             = "updated_at"
    }

    init(from profile: UserProfile, userId: String) {
        let iso = ISO8601DateFormatter()
        iso.formatOptions = [.withFullDate]
        self.id                    = userId
        self.displayName           = profile.displayName
        self.dateOfBirth           = profile.dateOfBirth.map { iso.string(from: $0) }
        self.biologicalSex         = profile.biologicalSexRawValue
        self.heightCm              = profile.heightCentimeters
        self.currentWeightKg       = profile.currentWeightKilograms
        self.targetWeightKg        = profile.targetWeightKilograms
        self.preferredWeightUnit   = profile.preferredWeightUnitRawValue
        self.preferredDistanceUnit = profile.preferredDistanceUnitRawValue
        self.onboardingCompleted   = profile.onboardingCompleted
        self.onboardingStep        = profile.onboardingStep
        self.updatedAt             = ISO8601DateFormatter().string(from: profile.updatedAt)
    }
}

// MARK: - Goal Profile DTO
// No `id` field — auto-generated by Postgres (gen_random_uuid()).
// Upsert uses onConflict: "user_id" so there's at most one row per user.

struct GoalProfileDTO: Codable {
    var userId: String
    var goals: [String]
    var primaryGoal: String?
    var activityLevel: String?
    var availableEquipment: [String]
    var workoutDaysPerWeek: Int
    var preferredWorkoutDurationMinutes: Int
    var updatedAt: String?

    enum CodingKeys: String, CodingKey {
        case userId                          = "user_id"
        case goals
        case primaryGoal                     = "primary_goal"
        case activityLevel                   = "activity_level"
        case availableEquipment              = "available_equipment"
        case workoutDaysPerWeek              = "workout_days_per_week"
        case preferredWorkoutDurationMinutes = "preferred_workout_duration_minutes"
        case updatedAt                       = "updated_at"
    }

    init(from profile: GoalProfile, userId: String) {
        self.userId                          = userId
        self.goals                           = profile.goalRawValues
        self.primaryGoal                     = profile.primaryGoalRawValue
        self.activityLevel                   = profile.activityLevelRawValue
        self.availableEquipment              = profile.availableEquipmentRawValues
        self.workoutDaysPerWeek              = profile.workoutDaysPerWeek
        self.preferredWorkoutDurationMinutes = profile.preferredWorkoutDurationMinutes
        self.updatedAt                       = ISO8601DateFormatter().string(from: profile.updatedAt)
    }
}

// MARK: - User Preference DTO
// No `id` field — auto-generated by Postgres.
// Upsert uses onConflict: "user_id".

struct UserPreferenceDTO: Codable {
    var userId: String
    var dietaryStyleValues: [String]
    var mealsPerDay: Int
    var wakeHour: Int
    var wakeMinute: Int
    var sleepHour: Int
    var sleepMinute: Int
    var workoutTimeHour: Int
    var workoutTimeMinute: Int
    var workdays: [Int]
    var updatedAt: String?

    enum CodingKeys: String, CodingKey {
        case userId              = "user_id"
        case dietaryStyleValues  = "dietary_style_values"
        case mealsPerDay         = "meals_per_day"
        case wakeHour            = "wake_hour"
        case wakeMinute          = "wake_minute"
        case sleepHour           = "sleep_hour"
        case sleepMinute         = "sleep_minute"
        case workoutTimeHour     = "workout_time_hour"
        case workoutTimeMinute   = "workout_time_minute"
        case workdays
        case updatedAt           = "updated_at"
    }

    init(from prefs: UserPreference, userId: String) {
        self.userId             = userId
        self.dietaryStyleValues = prefs.dietaryStyleRawValues
        self.mealsPerDay        = prefs.mealsPerDay
        self.wakeHour           = prefs.wakeHour
        self.wakeMinute         = prefs.wakeMinute
        self.sleepHour          = prefs.sleepHour
        self.sleepMinute        = prefs.sleepMinute
        self.workoutTimeHour    = prefs.workoutTimeHour
        self.workoutTimeMinute  = prefs.workoutTimeMinute
        self.workdays           = prefs.workdays
        self.updatedAt          = ISO8601DateFormatter().string(from: prefs.updatedAt)
    }
}

// MARK: - Meal Entry DTO

struct MealEntryDTO: Codable {
    var id: String
    var userId: String
    var consumedAt: String
    var mealType: String
    var title: String
    var calories: Double
    var proteinGrams: Double?
    var carbohydrateGrams: Double?
    var fatGrams: Double?
    var source: String

    enum CodingKeys: String, CodingKey {
        case id
        case userId            = "user_id"
        case consumedAt        = "consumed_at"
        case mealType          = "meal_type"
        case title
        case calories
        case proteinGrams      = "protein_grams"
        case carbohydrateGrams = "carbohydrate_grams"
        case fatGrams          = "fat_grams"
        case source
    }

    init(from entry: MealEntry, userId: String) {
        self.id                = entry.id.uuidString
        self.userId            = userId
        self.consumedAt        = ISO8601DateFormatter().string(from: entry.consumedAt)
        self.mealType          = entry.mealTypeRawValue
        self.title             = entry.title
        self.calories          = entry.calories
        self.proteinGrams      = entry.proteinGrams
        self.carbohydrateGrams = entry.carbohydrateGrams
        self.fatGrams          = entry.fatGrams
        self.source            = entry.sourceRawValue
    }
}

// MARK: - Water Entry DTO

struct WaterEntryDTO: Codable {
    var id: String
    var userId: String
    var loggedAt: String
    var amountMilliliters: Double
    var source: String

    enum CodingKeys: String, CodingKey {
        case id
        case userId            = "user_id"
        case loggedAt          = "logged_at"
        case amountMilliliters = "amount_milliliters"
        case source
    }

    init(from entry: WaterEntry, userId: String) {
        self.id                = entry.id.uuidString
        self.userId            = userId
        self.loggedAt          = ISO8601DateFormatter().string(from: entry.loggedAt)
        self.amountMilliliters = entry.amountMilliliters
        self.source            = entry.source
    }
}

// MARK: - Weight Entry DTO

struct WeightEntryDTO: Codable {
    var id: String
    var userId: String
    var loggedAt: String
    var weightKilograms: Double
    var notes: String?
    var source: String

    enum CodingKeys: String, CodingKey {
        case id
        case userId          = "user_id"
        case loggedAt        = "logged_at"
        case weightKilograms = "weight_kilograms"
        case notes
        case source
    }

    init(from entry: WeightEntry, userId: String) {
        self.id              = entry.id.uuidString
        self.userId          = userId
        self.loggedAt        = ISO8601DateFormatter().string(from: entry.loggedAt)
        self.weightKilograms = entry.weightKilograms
        self.notes           = entry.notes
        self.source          = entry.source
    }
}

// MARK: - Workout Session DTO
// Exercise logs (sets/reps/weight) are local-only in V1; only session metadata is synced.

struct WorkoutSessionDTO: Codable {
    var id: String
    var userId: String
    var startedAt: String
    var endedAt: String?
    var workoutGoal: String
    var title: String
    var notes: String?
    var totalEnergyKilocalories: Double?
    var durationSeconds: Double?
    var isCompleted: Bool
    var perceivedExertionLevel: Int?
    var source: String

    enum CodingKeys: String, CodingKey {
        case id
        case userId                  = "user_id"
        case startedAt               = "started_at"
        case endedAt                 = "ended_at"
        case workoutGoal             = "workout_goal"
        case title
        case notes
        case totalEnergyKilocalories = "total_energy_kilocalories"
        case durationSeconds         = "duration_seconds"
        case isCompleted             = "is_completed"
        case perceivedExertionLevel  = "perceived_exertion_level"
        case source
    }

    init(from session: WorkoutSession, userId: String) {
        let iso = ISO8601DateFormatter()
        self.id                      = session.id.uuidString
        self.userId                  = userId
        self.startedAt               = iso.string(from: session.startedAt)
        self.endedAt                 = session.endedAt.map { iso.string(from: $0) }
        self.workoutGoal             = session.workoutGoalRawValue
        self.title                   = session.title
        self.notes                   = session.notes
        self.totalEnergyKilocalories = session.totalEnergyKilocalories
        self.durationSeconds         = session.durationSeconds
        self.isCompleted             = session.isCompleted
        self.perceivedExertionLevel  = session.perceivedExertionLevel
        self.source                  = session.source
    }
}
